import { useEffect, useState } from "react";
import { CreditCard, Plus, X } from "lucide-react";
import { createId, store } from "@/lib/local-store";

type Language = "ar" | "en";
type Method = { id: string; nameAr: string; nameEn: string; kind: string };
type Tender = { key: string; methodId: string; amount: string; tendered: string; reference: string };
const text = { ar: { title: "الدفع", due: "المستحق", method: "طريقة الدفع", amount: "المبلغ", tendered: "المستلم", reference: "مرجع العملية", split: "إضافة دفعة", change: "الباقي", pay: "إتمام الدفع", close: "إغلاق", none: "لا توجد وسائل دفع مفعلة لهذا الفرع", invalid: "يجب أن يساوي مجموع الدفعات المستحق", failed: "تعذر تسجيل الدفع", paid: "تم الدفع بنجاح" }, en: { title: "Payment", due: "Amount due", method: "Payment method", amount: "Amount", tendered: "Tendered", reference: "Terminal reference", split: "Add tender", change: "Change", pay: "Complete payment", close: "Close", none: "No active payment methods are configured for this branch", invalid: "Tender amounts must equal the amount due", failed: "Unable to post payment", paid: "Payment completed" } } as const;

export function PaymentDialog({ language, orderId, branchId, total, onClose }: { language: Language; orderId: string; branchId: string; total: number; onClose: () => void }) {
  const t = text[language]; const [methods, setMethods] = useState<Method[]>([]); const [tenders, setTenders] = useState<Tender[]>([]); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const auth = (path: string, init?: RequestInit) => fetch(path, { ...init, headers: { "Content-Type": "application/json", Authorization: `Bearer ${store.get<string>("session-token") ?? ""}`, ...(init?.headers ?? {}) } });
  useEffect(() => { void (async () => { const response = await auth(`/api/v1/payment-methods?branchId=${branchId}`); if (!response.ok) return; const value = await response.json() as Method[]; setMethods(value); if (value[0]) setTenders([{ key: createId(), methodId: value[0].id, amount: total.toFixed(3), tendered: total.toFixed(3), reference: "" }]); })(); }, [branchId, total]);
  const number = (value: string) => Number(value) || 0; const applied = tenders.reduce((sum, x) => sum + number(x.amount), 0); const change = tenders.reduce((sum, x) => sum + (methods.find((m) => m.id === x.methodId)?.kind === "Cash" ? Math.max(0, number(x.tendered) - number(x.amount)) : 0), 0);
  function update(key: string, patch: Partial<Tender>) { setTenders(tenders.map((x) => x.key === key ? { ...x, ...patch } : x)); }
  async function pay() { setMessage(""); if (Math.abs(applied - total) > 0.0001 || tenders.some((x) => number(x.amount) <= 0 || number(x.tendered) <= 0)) { setMessage(t.invalid); return; } setSaving(true); try { const response = await auth(`/api/v1/orders/${orderId}/payments`, { method: "POST", body: JSON.stringify({ payments: tenders.map((x) => ({ clientRequestId: createId(), paymentMethodId: x.methodId, amount: number(x.amount), tenderedAmount: number(x.tendered), status: "Captured", providerReference: x.reference.trim() || null })) }) }); if (!response.ok) { const problem = await response.json().catch(() => null); throw new Error(problem?.errors?.payments?.[0] ?? t.failed); } setMessage(t.paid); } catch (error) { setMessage(error instanceof Error ? error.message : t.failed); } finally { setSaving(false); } }
  return <div className="fixed inset-0 z-50 grid place-items-end bg-black/35 sm:place-items-center sm:p-5"><section role="dialog" aria-modal="true" aria-label={t.title} className="max-h-[92vh] w-full max-w-xl overflow-y-auto rounded-t-2xl bg-[#f5f6f2] p-5 shadow-2xl sm:rounded-2xl sm:p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-[#0e5a4f]">{t.title}</p><h2 className="text-2xl font-bold">OMR {total.toFixed(3)}</h2></div><button aria-label={t.close} onClick={onClose} className="grid size-11 place-items-center rounded-lg bg-white"><X size={19} /></button></div>{methods.length === 0 ? <p role="alert" className="mt-6 rounded-xl bg-[#fff5f4] p-4 text-sm text-[#9b2922]">{t.none}</p> : <><div className="mt-5 space-y-3">{tenders.map((x, index) => <div key={x.key} className="rounded-xl border border-[#dfe5df] bg-white p-4"><div className="flex justify-between"><strong>{t.method} {index + 1}</strong>{tenders.length > 1 && <button onClick={() => setTenders(tenders.filter((item) => item.key !== x.key))}>×</button>}</div><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm">{t.method}<select value={x.methodId} onChange={(e) => update(x.key, { methodId: e.target.value })} className="mt-1 min-h-11 w-full rounded-lg border px-3">{methods.map((m) => <option key={m.id} value={m.id}>{language === "ar" ? m.nameAr : m.nameEn}</option>)}</select></label><label className="text-sm">{t.amount}<input inputMode="decimal" value={x.amount} onChange={(e) => update(x.key, { amount: e.target.value })} className="mt-1 min-h-11 w-full rounded-lg border px-3" /></label><label className="text-sm">{t.tendered}<input inputMode="decimal" value={x.tendered} onChange={(e) => update(x.key, { tendered: e.target.value })} className="mt-1 min-h-11 w-full rounded-lg border px-3" /></label><label className="text-sm">{t.reference}<input value={x.reference} onChange={(e) => update(x.key, { reference: e.target.value })} className="mt-1 min-h-11 w-full rounded-lg border px-3" /></label></div></div>)}</div><button onClick={() => methods[0] && setTenders([...tenders, { key: createId(), methodId: methods[0].id, amount: "", tendered: "", reference: "" }])} className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-lg border border-[#0e5a4f] px-4 font-semibold text-[#0e5a4f]"><Plus size={17} />{t.split}</button><div className="mt-5 flex justify-between rounded-xl bg-white p-4"><span>{t.change}</span><strong>OMR {change.toFixed(3)}</strong></div>{message && <p role="status" className={`mt-4 text-sm ${message === t.paid ? "text-[#137347]" : "text-[#b4322a]"}`}>{message}</p>}<button disabled={saving || message === t.paid} onClick={() => void pay()} className="mt-5 flex min-h-13 w-full items-center justify-center gap-2 rounded-xl bg-[#0e5a4f] font-semibold text-white disabled:opacity-60"><CreditCard size={18} />{saving ? "..." : t.pay}</button></>}</section></div>;
}
