import { useEffect, useState } from "react";
import { Plus, RefreshCw } from "lucide-react";
import { store } from "@/lib/local-store";

type Language = "ar" | "en";
type Product = { id: string; nameAr: string; nameEn: string };
type Branch = { id: string; nameAr: string; nameEn: string };
type Channel = { id: string; code: string; nameAr: string; nameEn: string; isActive: boolean };
type TaxCategory = { id: string; code: string; nameAr: string; nameEn: string };
const words = { ar: { title: "التسعير والضريبة", subtitle: "قواعد مؤرخة تحفظ الأسعار والضريبة الصحيحة عند البيع.", channels: "قنوات البيع", prices: "قواعد الأسعار", taxes: "قواعد الضريبة", promos: "العروض", add: "إضافة", code: "الرمز", nameAr: "الاسم بالعربية", nameEn: "الاسم بالإنجليزية", product: "الصنف", branch: "الفرع", channel: "القناة", price: "السعر", rate: "النسبة", from: "من", to: "إلى", inclusive: "شامل الضريبة", exclusive: "غير شامل الضريبة", save: "حفظ القاعدة", loading: "جارٍ التحميل", retry: "إعادة المحاولة", noData: "لا توجد إعدادات بعد", error: "تعذر حفظ الإعداد.", promotionCode: "رمز العرض", discount: "الخصم", percentage: "نسبة مئوية", fixed: "مبلغ ثابت", priority: "الأولوية", active: "نشط" }, en: { title: "Pricing & tax", subtitle: "Effective-dated rules preserve the price and tax that apply at sale time.", channels: "Sales channels", prices: "Price rules", taxes: "Tax rules", promos: "Promotions", add: "Add", code: "Code", nameAr: "Arabic name", nameEn: "English name", product: "Product", branch: "Branch", channel: "Channel", price: "Price", rate: "Rate", from: "From", to: "To", inclusive: "Tax inclusive", exclusive: "Tax exclusive", save: "Save rule", loading: "Loading", retry: "Retry", noData: "No settings yet", error: "Unable to save the setting.", promotionCode: "Promotion code", discount: "Discount", percentage: "Percentage", fixed: "Fixed amount", priority: "Priority", active: "Active" } } as const;
const date = () => new Date().toISOString().slice(0, 16);

export function PricingSection({ language }: { language: Language }) {
  const t = words[language]; const [tab, setTab] = useState<"channels" | "prices" | "taxes" | "promos">("channels"); const [products, setProducts] = useState<Product[]>([]); const [branches, setBranches] = useState<Branch[]>([]); const [channels, setChannels] = useState<Channel[]>([]); const [taxCategories, setTaxCategories] = useState<TaxCategory[]>([]); const [items, setItems] = useState<any[]>([]); const [state, setState] = useState<"loading" | "idle" | "error">("loading"); const [error, setError] = useState("");
  const name = (item: { nameAr: string; nameEn: string }) => language === "ar" ? item.nameAr : item.nameEn;
  const auth = (path: string, init?: RequestInit) => fetch(path, { ...init, headers: { "Content-Type": "application/json", Authorization: `Bearer ${store.get<string>("session-token") ?? ""}`, ...(init?.headers ?? {}) } });
  async function load() { setState("loading"); try { const endpoint = tab === "channels" ? "/sales-channels" : tab === "prices" ? "/price-rules" : tab === "taxes" ? "/tax-rules" : "/promotions"; const [itemResponse, productResponse, branchResponse, channelResponse, taxResponse] = await Promise.all([auth(endpoint), auth("/products"), auth("/branches"), auth("/sales-channels"), auth("/tax-categories")]); if (![itemResponse, productResponse, branchResponse, channelResponse, taxResponse].every((response) => response.ok)) throw new Error(); setItems(await itemResponse.json()); setProducts(await productResponse.json()); setBranches(await branchResponse.json()); setChannels(await channelResponse.json()); setTaxCategories(await taxResponse.json()); setState("idle"); } catch { setState("error"); } }
  useEffect(() => { void load(); }, [tab]);
  async function create(path: string, body: unknown) { setError(""); const response = await auth(path, { method: "POST", body: JSON.stringify(body) }); if (!response.ok) { setError(t.error); return false; } await load(); return true; }
  return <><p className="text-sm font-semibold text-[#0e5a4f]">{t.title}</p><h1 className="mt-2 text-2xl font-semibold tracking-tight sm:text-3xl">{t.title}</h1><p className="mt-2 max-w-2xl text-[#64716b]">{t.subtitle}</p><div className="mt-6 flex gap-2 overflow-x-auto border-b border-[#dfe5df]">{(["channels", "prices", "taxes", "promos"] as const).map((key) => <button key={key} onClick={() => setTab(key)} className={`min-h-11 shrink-0 border-b-2 px-3 text-sm font-semibold ${tab === key ? "border-[#0e5a4f] text-[#0e5a4f]" : "border-transparent text-[#64716b]"}`}>{t[key]}</button>)}</div>{tab === "channels" && <ChannelForm t={t} onSave={(body: unknown) => create("/sales-channels", body)} />}{tab === "prices" && <PriceForm t={t} products={products} branches={branches} channels={channels} onSave={(body: unknown) => create("/price-rules", body)} />}{tab === "taxes" && <TaxForm t={t} categories={taxCategories} branches={branches} onSave={(body: unknown) => create("/tax-rules", body)} />}{tab === "promos" && <PromotionForm t={t} products={products} branches={branches} channels={channels} onSave={(body: unknown) => create("/promotions", body)} />}{error && <p role="alert" className="mt-4 text-sm text-[#b4322a]">{error}</p>}{state === "loading" ? <div className="mt-8 flex items-center gap-2 text-sm text-[#64716b]"><RefreshCw className="animate-spin" size={18} />{t.loading}</div> : state === "error" ? <button onClick={() => void load()} className="mt-8 rounded-lg border px-4 py-2 text-sm font-semibold">{t.retry}</button> : <RulesList items={items} t={t} name={name} products={products} branches={branches} channels={channels} categories={taxCategories} />}</>;
}
function Select({ label, value, onChange, options, optional = false }: { label: string; value: string; onChange: (value: string) => void; options: Array<{ id: string; label: string }>; optional?: boolean }) { return <label className="block text-sm font-medium">{label}<select value={value} onChange={(e) => onChange(e.target.value)} className="mt-2 min-h-12 w-full rounded-lg border border-[#cdd7d0] bg-white px-3">{optional && <option value="">-</option>}{options.map((x) => <option key={x.id} value={x.id}>{x.label}</option>)}</select></label>; }
function Input({ label, value, onChange, type = "text", required = true }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label className="block text-sm font-medium">{label}<input required={required} type={type} value={value} onChange={(e) => onChange(e.target.value)} className="mt-2 min-h-12 w-full rounded-lg border border-[#cdd7d0] px-3" /></label>; }
function ChannelForm({ t, onSave }: { t: any; onSave: (body: any) => Promise<boolean> }) { const [f, set] = useState({ code: "", nameAr: "", nameEn: "" }); return <form onSubmit={async (e) => { e.preventDefault(); if (await onSave(f)) set({ code: "", nameAr: "", nameEn: "" }); }} className="mt-5 rounded-xl border border-[#dfe5df] bg-white p-5"><div className="grid gap-4 sm:grid-cols-3"><Input label={t.code} value={f.code} onChange={(code) => set({ ...f, code })} /><Input label={t.nameAr} value={f.nameAr} onChange={(nameAr) => set({ ...f, nameAr })} /><Input label={t.nameEn} value={f.nameEn} onChange={(nameEn) => set({ ...f, nameEn })} /></div><Save t={t} /></form>; }
function PriceForm({ t, products, branches, channels, onSave }: any) { const [f, set] = useState({ productId: "", branchId: "", salesChannelId: "", price: "", effectiveFrom: date(), effectiveTo: "" }); return <form onSubmit={(e) => { e.preventDefault(); void onSave({ ...f, branchId: f.branchId || null, salesChannelId: f.salesChannelId || null, price: Number(f.price), effectiveFrom: new Date(f.effectiveFrom).toISOString(), effectiveTo: f.effectiveTo ? new Date(f.effectiveTo).toISOString() : null }); }} className="mt-5 rounded-xl border border-[#dfe5df] bg-white p-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Select label={t.product} value={f.productId} onChange={(productId) => set({ ...f, productId })} options={products.map((x: Product) => ({ id: x.id, label: x.nameAr }))} /><Select optional label={t.branch} value={f.branchId} onChange={(branchId) => set({ ...f, branchId })} options={branches.map((x: Branch) => ({ id: x.id, label: x.nameAr }))} /><Select optional label={t.channel} value={f.salesChannelId} onChange={(salesChannelId) => set({ ...f, salesChannelId })} options={channels.map((x: Channel) => ({ id: x.id, label: x.nameAr }))} /><Input label={t.price} type="number" value={f.price} onChange={(price) => set({ ...f, price })} /><Input label={t.from} type="datetime-local" value={f.effectiveFrom} onChange={(effectiveFrom) => set({ ...f, effectiveFrom })} /><Input label={t.to} type="datetime-local" required={false} value={f.effectiveTo} onChange={(effectiveTo) => set({ ...f, effectiveTo })} /></div><Save t={t} /></form>; }
function TaxForm({ t, categories, branches, onSave }: any) { const [f, set] = useState({ taxCategoryId: "", branchId: "", rate: "", calculationMode: "Exclusive", effectiveFrom: date(), effectiveTo: "" }); return <form onSubmit={(e) => { e.preventDefault(); void onSave({ ...f, branchId: f.branchId || null, rate: Number(f.rate), effectiveFrom: new Date(f.effectiveFrom).toISOString(), effectiveTo: f.effectiveTo ? new Date(f.effectiveTo).toISOString() : null }); }} className="mt-5 rounded-xl border border-[#dfe5df] bg-white p-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Select label={t.taxes} value={f.taxCategoryId} onChange={(taxCategoryId) => set({ ...f, taxCategoryId })} options={categories.map((x: TaxCategory) => ({ id: x.id, label: x.nameAr }))} /><Select optional label={t.branch} value={f.branchId} onChange={(branchId) => set({ ...f, branchId })} options={branches.map((x: Branch) => ({ id: x.id, label: x.nameAr }))} /><Input label={t.rate} type="number" value={f.rate} onChange={(rate) => set({ ...f, rate })} /><Select label={t.taxes} value={f.calculationMode} onChange={(calculationMode) => set({ ...f, calculationMode })} options={[{ id: "Exclusive", label: t.exclusive }, { id: "Inclusive", label: t.inclusive }]} /><Input label={t.from} type="datetime-local" value={f.effectiveFrom} onChange={(effectiveFrom) => set({ ...f, effectiveFrom })} /><Input label={t.to} type="datetime-local" required={false} value={f.effectiveTo} onChange={(effectiveTo) => set({ ...f, effectiveTo })} /></div><Save t={t} /></form>; }
function PromotionForm({ t, products, branches, channels, onSave }: any) { const [f, set] = useState({ code: "", nameAr: "", nameEn: "", productId: "", branchId: "", salesChannelId: "", discountType: "Percentage", discountValue: "", priority: "0", effectiveFrom: date(), effectiveTo: "" }); return <form onSubmit={(e) => { e.preventDefault(); void onSave({ ...f, productId: f.productId || null, branchId: f.branchId || null, salesChannelId: f.salesChannelId || null, discountValue: Number(f.discountValue), priority: Number(f.priority), effectiveFrom: new Date(f.effectiveFrom).toISOString(), effectiveTo: f.effectiveTo ? new Date(f.effectiveTo).toISOString() : null }); }} className="mt-5 rounded-xl border border-[#dfe5df] bg-white p-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Input label={t.promotionCode} value={f.code} onChange={(code) => set({ ...f, code })} /><Input label={t.nameAr} value={f.nameAr} onChange={(nameAr) => set({ ...f, nameAr })} /><Input label={t.nameEn} value={f.nameEn} onChange={(nameEn) => set({ ...f, nameEn })} /><Select optional label={t.product} value={f.productId} onChange={(productId) => set({ ...f, productId })} options={products.map((x: Product) => ({ id: x.id, label: x.nameAr }))} /><Select optional label={t.branch} value={f.branchId} onChange={(branchId) => set({ ...f, branchId })} options={branches.map((x: Branch) => ({ id: x.id, label: x.nameAr }))} /><Select optional label={t.channel} value={f.salesChannelId} onChange={(salesChannelId) => set({ ...f, salesChannelId })} options={channels.map((x: Channel) => ({ id: x.id, label: x.nameAr }))} /><Select label={t.discount} value={f.discountType} onChange={(discountType) => set({ ...f, discountType })} options={[{ id: "Percentage", label: t.percentage }, { id: "FixedAmount", label: t.fixed }]} /><Input label={t.discount} type="number" value={f.discountValue} onChange={(discountValue) => set({ ...f, discountValue })} /><Input label={t.priority} type="number" value={f.priority} onChange={(priority) => set({ ...f, priority })} /><Input label={t.from} type="datetime-local" value={f.effectiveFrom} onChange={(effectiveFrom) => set({ ...f, effectiveFrom })} /><Input label={t.to} type="datetime-local" required={false} value={f.effectiveTo} onChange={(effectiveTo) => set({ ...f, effectiveTo })} /></div><Save t={t} /></form>; }
function Save({ t }: { t: any }) { return <button className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-lg bg-[#0e5a4f] px-4 font-semibold text-white"><Plus size={18} />{t.save}</button>; }
function RulesList({ items, t }: any) { return <section className="mt-6 rounded-xl border border-[#dfe5df] bg-white">{items.length === 0 ? <p className="p-7 text-sm text-[#64716b]">{t.noData}</p> : <div className="divide-y divide-[#e8ece8]">{items.map((item: any) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 p-4 text-sm"><strong>{item.code ?? item.price ?? item.rate ?? item.discountValue}</strong><span className="text-[#64716b]">{item.effectiveFrom ? new Date(item.effectiveFrom).toLocaleString() : item.nameAr}</span></div>)}</div>}</section>; }
