import { useState } from "react";
import { store } from "@/lib/local-store";
type User = { id: string; username: string; email: string | null; displayName: string; isActive: boolean; branchIds: string[] };
export function UserEditor({ user, branches, language, auth, onClose, onSaved }: { user: User; branches: { id: string; nameAr: string; nameEn: string }[]; language: "ar" | "en"; auth: (p: string, i?: RequestInit) => Promise<Response>; onClose: () => void; onSaved: () => void }) {
  const ar = language === "ar";
  const [form, setForm] = useState({ ...user, email: user.email ?? "", password: "" });
  const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function save(e: React.FormEvent) {
    e.preventDefault(); if (saving) return; setSaving(true); setError("");
    try { const r = await auth(`/api/v1/users/${user.id}`, { method: "PUT", body: JSON.stringify({ ...form, email: form.email || null, password: form.password || null }) }); if (!r.ok) throw new Error(); const result = await r.json() as { signInRequired: boolean }; if (result.signInRequired) { store.remove("session-token"); window.location.reload(); return; } onSaved(); }
    catch { setError(ar ? "تعذر الحفظ. تحقق من عدم تكرار اسم المستخدم، وصحة البريد، وتخصيص فرع. لا يمكنك إيقاف حسابك الحالي." : "Unable to save. Check for a duplicate username, a valid email and an assigned branch. You cannot deactivate your own account."); } finally { setSaving(false); }
  }
  return <form onSubmit={save} className="mt-5 space-y-4 rounded-xl border border-[#0e5a4f] bg-white p-5"><h2 className="font-bold">{ar ? "تعديل المستخدم" : "Edit user"}: {user.displayName}</h2><div className="grid gap-4 sm:grid-cols-2">{(["username", "displayName", "email", "password"] as const).map(key => <label key={key} className="text-sm">{{ username: ar ? "اسم المستخدم *" : "Username *", displayName: ar ? "الاسم الظاهر *" : "Display name *", email: ar ? "البريد الإلكتروني (اختياري)" : "Email (optional)", password: ar ? "كلمة مرور جديدة (اتركها فارغة للإبقاء على الحالية)" : "New password (leave blank to keep current)" }[key]}<input required={key === "username" || key === "displayName"} type={key === "password" ? "password" : key === "email" ? "email" : "text"} minLength={key === "password" ? 8 : key === "username" ? 3 : undefined} maxLength={key === "username" ? 40 : 160} autoComplete={key === "password" ? "new-password" : "off"} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} className="mt-1 min-h-11 w-full rounded-lg border px-3" /></label>)}</div><fieldset><legend className="text-sm font-medium">{ar ? "الفروع المخصصة *" : "Assigned branches *"}</legend><div className="flex flex-wrap gap-4">{branches.map(b => <label key={b.id} className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={form.branchIds.includes(b.id)} onChange={e => setForm({ ...form, branchIds: e.target.checked ? [...form.branchIds, b.id] : form.branchIds.filter(id => id !== b.id) })} />{ar ? b.nameAr : b.nameEn}</label>)}</div></fieldset><label className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={form.isActive} onChange={e => setForm({ ...form, isActive: e.target.checked })} />{ar ? "الحساب نشط" : "Account active"}</label><p className="text-xs text-[#64716b]">{ar ? "سيحتاج المستخدم إلى تسجيل الدخول مجددًا بعد تعديل بياناته." : "The user will need to sign in again after these changes."}</p>{error && <p role="alert" className="text-sm text-red-700">{error}</p>}<div className="flex gap-3"><button disabled={saving || !form.branchIds.length} className="min-h-11 rounded-lg bg-[#0e5a4f] px-4 font-semibold text-white">{ar ? "حفظ التعديلات" : "Save changes"}</button><button type="button" disabled={saving} onClick={onClose} className="min-h-11 rounded-lg border px-4">{ar ? "إلغاء" : "Cancel"}</button></div></form>;
}
