using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace OFC.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddReadableOrderTracking : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Starting at 100 keeps the customer-facing number short and readable. PostgreSQL assigns a
            // distinct sequence value to every existing row while adding the identity column, so the
            // unique index below is safe on an already-populated production database.
            migrationBuilder.Sql("""
                ALTER TABLE ofc.orders
                ADD COLUMN "Number" bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 100);
                """);

            migrationBuilder.CreateIndex(
                name: "IX_orders_Number",
                schema: "ofc",
                table: "orders",
                column: "Number",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_orders_Number",
                schema: "ofc",
                table: "orders");

            migrationBuilder.DropColumn(
                name: "Number",
                schema: "ofc",
                table: "orders");
        }
    }
}
